# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Patrick van de Sluis
title: Process Manager
email: patrick@vandesluis.com
website: patrickvandesluis.nl

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: patrickvdsluis
github_username:  patrickvandesluis
stackoverflow_username: "15013147"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: patrickvandesluis
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: 
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: test.nl
#   icon: fas fa-globe
#   url: https://test.nl
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-111597809-1"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Patrick and I am a Process Manager at Ebben Nurseries. Here I work with my collegues to improve the business processes and the customer experience for multiple companies related to the Ebbenhout Holding.
  I characterize myself as a driven problem solver who works best in small teams, where I have no issue taking the lead.

  In my free time I like to hack away at [hackthebox.eu](https://hackthebox.eu), building my [Home Assistant](https://www.home-assistant.io/) setup or go swimming.

  I am most skilled in: <mark>Lean Project Management</mark>, <mark>SQL</mark>, <mark>Python</mark> and <mark>React</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Process Manager
        link: ebben.nl
        # link_text: 
        sub_title: Ebben Nurseries
        caption: October 2017 - Current
        quote: >
          Data is not information, Information is not knowledge, Knowledge is not understanding, Understanding is not wisdom.
          - Clifford Stoll
        description: | # this will include new lines to allow paragraphs
              #### Projects include:
              - Digitizing the supply chain
              - Process automation
              - Advanced BI reporting
              - PoC Development
              - Member of Tenderteam


              #### Positions:
              **Process Manager** - Jun 2019 - Current

              **Interim Logistics Manager Benelux** - Dec 2018 - Jun 2019

              **Business Analist** - Oct 2017 - Dec 2018
      - layout: left
        title: Entrepreneur
        # sub_title: 
        caption: September 2015 - October 2017
        # quote: >
          # .
        description: | # this will include new lines to allow paragraphs
              Trading various ingame and cryto currencies. Maintaining PHP Laravel Framework for managing miners.
      - layout: left
        title: ERP Implementation
        link: vlastuin.nl
        sub_title: Vlastuin Group
        caption: September 2013 - October 2015
        # quote: >
          # .
        description: | # this will include new lines to allow paragraphs
              #### Positions:

              **BI Specialist** - Jan 2015 - Oct 2015

              **Projectmember ERP integration** - Jun 2014 - Sep 2014

              **Trainee ERP integration** - Sep 2013 - Jun 2014
      - layout: left
        title: Trainee
        link: metaglas.nl
        sub_title: Metaglas
        caption: April 2012 - June 2013
        # quote: >
          # .
        description: | # this will include new lines to allow paragraphs
              Writing a manual for manufacturing processes. Reduced inventory cost by implementing ABC analysis.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BBA Logistics and Economics
        caption: 2011 - 2018
        sub_title: Utrecht University of Applied Science
        # quote: >
        #   .
        description: | # this will include new lines to allow paragraphs
          I wrote my thesis on supply and demand forecasting, with a minor in People Management.
          
          During my study I also pursued side projects.
      - layout: left
        title: HAVO - E&M
        caption: 2005 - 2011
        sub_title: Ichthus College - Veenendaal
        # quote: >
        #   .
        description: | # this will include new lines to allow paragraphs
          Senior General Secondary Education with a focus on Economics and Society.

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TALIS FlexTools
        caption: 2019
        sub_title: TANS
        description:
          Training in maintaining the Talis TMS for use within Ebben Nurseries.
      - layout: left
        title: Python for Data Science and Machine Learning Bootcamp
        caption: 2018
        sub_title: Udemy
        # quote: >
        #   .
        description: | # this will include new lines to allow paragraphs
          A course to strenghten my knowledge on the topic of Machine Learning and Data Science. I used the lessons learned when writing my thesis.

  - title: Additional skills
    layout: text
    content: | # this will include new lines to allow paragraphs

      ***** - SQL (Oracle, Mysql, Postgres, Sybase, Interbase)

      ***\* - Python (Flask, Django, Pandas)
      
      ***\* - Javascript (React, jQuery, Redux)

      ***\* - Team player

      ***\* - Dynamics 365
      
      ***\* - Fujitsu Glovia G2

      *** - Project Managemnt
      
      *** - SAP Crystal Reports & Fast Reports

      *** - Docker

      *** - LEMP Stack


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
